name: core_error
description: "核心错误体系：统一异常基类与网络/存储/配置异常。"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.13.3

resolution: workspace

dependencies:
  meta: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
